### ISSUE TITLE
生成文档没有图片

### ISSUE THREAD

**Issue by wei5687** [zkep/my-geektime#38]
文档只有文字，图片能生成出来吗

**Comment by zkep** [comment]
> 文档只有文字，图片能生成出来吗

本地docker部署的会有图片的，线上体验就只是展示功能（没有流量）

**Comment by wei5687** [comment]
虚拟机docker部署项目也不行吗？

**Comment by zkep** [comment]
> 虚拟机docker部署项目也不行吗？

可以的，可以看下文档的html页面内容，返回的图片链接是否存在，存在的情况下是否可以访问到图片内容

**Comment by wei5687** [comment]
我应该怎么把文档的本机地址，全部改成虚拟机地址？docker拉取的项目的镜像文件，是不是要把源文件下载到虚拟机来修改，再把它部署到docker运行？

**Comment by zkep** [comment]
> 我应该怎么把文档的本机地址，全部改成虚拟机地址？docker拉取的项目的镜像文件，是不是要把源文件下载到虚拟机来修改，再把它部署到docker运行？

如果不是本机IP的情况下，可以修改下这两个地方的配置，可以试试

https://github.com/zkep/my-geektime/blob/master/docker/server/config.yml 修改下配置里的

storage的 host 修改成你访问的ip端口
```yaml
storage: # mp4 or mp3 save folder
  driver: local
  directory: repo 
  bucket: object
  host:  http://127.0.0.1:8090  
```
proxy的 proxy_url 修改成你访问的ip端口
```
 proxy:
    cache: true
    cache_prefix: resource
    proxy_url: http://127.0.0.1:8090/v2/file/proxy?url={url}
    urls:
      - https://static001.geekbang.org/resource/image
      - https://static001.geekbang.org/account/avatar
```
